const fs=require('fs'),vm=require('vm'),assert=require('assert');
const context={document:{addEventListener(){}},esc:String,rows:events=>'rows:'+events.length};
vm.createContext(context);
vm.runInContext(fs.readFileSync('china-provinces.js','utf8'),context);
vm.runInContext(fs.readFileSync('city-data.js','utf8'),context);
vm.runInContext(fs.readFileSync('footprint-map.js','utf8'),context);
assert(vm.runInContext('chinaCityData.length',context)===34);
assert(vm.runInContext('chinaCityRecords.length',context)>=390);
assert(vm.runInContext('chinaCityRecords.every(city=>Number.isFinite(city.lng)&&Number.isFinite(city.lat))',context));
const html=vm.runInContext("footprintMap([{city:'上海市',status:'attended'},{city:'上海',status:'attended'},{city:'嘉兴市',status:'attended'},{city:'杭州',status:'pending'},{city:'未知城市',status:'attended'}])",context);
assert(html.includes('已点亮 2 座城市'));
assert(html.includes('上海市，2 场现场'));
assert(html.includes('嘉兴市，1 场现场'));
assert(!html.includes('嘉兴市 1 场</span> · 待定位'));
assert(!html.includes('data-map-city="杭州"'));
assert(html.includes('未知城市'));
assert(html.includes('北京市'));
assert(html.includes('省级行政区底图'));
assert(!html.includes('NaN'));
assert(!html.includes('fill="#535767"'));
assert(vm.runInContext("resolveCityName('浙江省嘉兴市')",context)==='嘉兴市');
assert(vm.runInContext("resolveCityName('嘉兴')",context)==='嘉兴市');
assert(vm.runInContext("resolveCityName('台北')",context)==='台北市');
assert(vm.runInContext("resolveCityName('澳门')",context)==='澳门特别行政区');
assert(vm.runInContext('footprintMap([])',context).includes('点亮第一座城市'));
console.log('Passed: attended-only, normalized cities, unknown cities, empty state.');
